# services:

#   mysql:
#     image: mysql:8.4
#     container_name: employee-mysql

#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${DB_NAME}
#       MYSQL_USER: ${DB_USER}
#       MYSQL_PASSWORD: ${DB_PASSWORD}

#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

#     networks:
#       - employee-network

#     healthcheck:
#       test:
#         [
#           "CMD",
#           "mysqladmin",
#           "ping",
#           "-h",
#           "localhost",
#           "-u",
#           "${DB_USER}",
#           "-p${DB_PASSWORD}"
#         ]
#       interval: 10s
#       timeout: 5s
#       retries: 10


#   fastapi:
#     build:
#       context: ./fastapi

#     container_name: employee-fastapi

#     env_file:
#       - .env

#     depends_on:
#       mysql:
#         condition: service_healthy

#     networks:
#       - employee-network


#   express:
#     build:
#       context: ./express

#     container_name: employee-express

#     env_file:
#       - .env

#     depends_on:
#       mysql:
#         condition: service_healthy

#     networks:
#       - employee-network


#   springboot:
#     build:
#       context: ./springboot

#     container_name: employee-springboot

#     env_file:
#       - .env

#     depends_on:
#       mysql:
#         condition: service_healthy

#     networks:
#       - employee-network


#   dotnet:
#     build:
#       context: ./dotnet

#     container_name: employee-dotnet

#     env_file:
#       - .env

#     depends_on:
#       mysql:
#         condition: service_healthy

#     networks:
#       - employee-network


#   nginx:
#     build:
#       context: ./nginx

#     container_name: employee-nginx

#     depends_on:
#       - fastapi
#       - express
#       - springboot
#       - dotnet

#     ports:
#       - "80:80"

#     networks:
#       - employee-network

#     # Mount nginx.conf from the host so NGINX configuration changes
#     # can be applied without rebuilding the Docker image.in dockerfile of the nginx we just copy the first version of the nginx.conf in the /etc/nginx/nginx.conf, but we can mount the host version of the nginx.conf to the container so that we can make changes to the nginx.conf without rebuilding the image. The :ro option makes the volume read-only, so the container cannot modify the host config.
#     # :ro = read-only, so the container cannot modify the host config.
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./nginx/logs:/var/log/nginx

#     # 1. Check the NGINX configuration for syntax/errors
#     #docker compose exec nginx nginx -t

#     #2. Recreate the NGINX container when Docker Compose settings change,
#     # such as adding/changing volumes, ports, networks, or environment variables.
#     #docker compose up -d --force-recreate nginx

#     # 3.Reload NGINX after changing only nginx.conf, without recreating the container.
#     #docker compose exec nginx nginx -s reload

#     # Persist NGINX logs on the host
    


# networks:

#   employee-network:
#     driver: bridge


# volumes:

#   mysql_data:






services:

  fastapi:
    build:
      context: ./fastapi

    container_name: employee-fastapi

    environment:
      DB_HOST: employee-rds.cl6u40kw03u6.ap-southeast-2.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: Vedant2003
      DB_NAME: employee_db
      DB_PORT: 3306

    networks:
      - employee-network


  express:
    build:
      context: ./express

    container_name: employee-express

    environment:
      DB_HOST: employee-rds.cl6u40kw03u6.ap-southeast-2.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: Vedant2003
      DB_NAME: employee_db
      DB_PORT: 3306

    networks:
      - employee-network


  springboot:
    build:
      context: ./springboot

    container_name: employee-springboot

    environment:
      DB_HOST: employee-rds.cl6u40kw03u6.ap-southeast-2.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: Vedant2003
      DB_NAME: employee_db
      DB_PORT: 3306

    networks:
      - employee-network


  dotnet:
    build:
      context: ./dotnet

    container_name: employee-dotnet

    environment:
      DB_HOST: employee-rds.cl6u40kw03u6.ap-southeast-2.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: Vedant2003
      DB_NAME: employee_db
      DB_PORT: 3306

    networks:
      - employee-network


  flyway:
    image: redgate/flyway
    container_name: employee-flyway

    command:
      - -url=jdbc:mysql://employee-rds.cl6u40kw03u6.ap-southeast-2.rds.amazonaws.com:3306/employee_db
      - -user=admin
      - -password=Vedant2003
      - -baselineOnMigrate=true
      - -baselineVersion=1
      - migrate

    volumes:
      - ./flyway:/flyway/sql:ro

    networks:
      - employee-network

    restart: "no"
#  From your project directory, run:

# docker compose run --rm flyway

# This starts a temporary Flyway container,
#  connects to RDS, checks the migration history, 
#  and applies pending migrations.

  nginx:
    build:
      context: ./nginx

    container_name: employee-nginx

    depends_on:
      - fastapi
      - express
      - springboot
      - dotnet

    ports:
      - "80:80"

    networks:
      - employee-network

    # Mount nginx.conf from the host so NGINX configuration changes
    # can be applied without rebuilding the Docker image.in dockerfile of the nginx we just copy the first version of the nginx.conf in the /etc/nginx/nginx.conf, but we can mount the host version of the nginx.conf to the container so that we can make changes to the nginx.conf without rebuilding the image. The :ro option makes the volume read-only, so the container cannot modify the host config.
    # :ro = read-only, so the container cannot modify the host config.
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx

    # 1. Check the NGINX configuration for syntax/errors
    #docker compose exec nginx nginx -t

    #2. Recreate the NGINX container when Docker Compose settings change,
    # such as adding/changing volumes, ports, networks, or environment variables.
    #docker compose up -d --force-recreate nginx

    # 3.Reload NGINX after changing only nginx.conf, without recreating the container.
    #docker compose exec nginx nginx -s reload

    # Persist NGINX logs on the host
    


networks:

  employee-network:
    driver: bridge